config/routes.rb
Rails.application.routes.draw do
  get 'ask', to: 'coaching#ask'

  get 'answer', to: 'coaching#answer'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coaching_controller.rb
class CoachingController < ApplicationController


  # def index
  # @category = params[:ask]
  # @coachings = COACHING.select {|c| c[:category] == @category }
  # end
  def ask

  end

  def answer
    @your_message = params[:question]
    @answer= coach(@your_message)

  end

private
  def coach(your_message)
    if @your_message.end_with?("?")
      @answer = "Silly question, get dressed and go to work!"
    else
      @answer = "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/views/coaching/answer.html.erb
<h1>Coaching#answer</h1>

<%= @answer %>

<%= link_to "answer again", ask_path %>

app/views/coaching/ask.html.erb
<h1>Coaching#ask</h1>
<p>Find me in app/views/coaching/ask.html.erb</p>
<form action="answer">
  <label for="question">Speak to your coach</label>
  <input type="text" id="question" name="question" placeholder="what time is it?">
  <input type="submit" value="Go on!">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>